### ISSUE TITLE
PNG in XDV is missing

### ISSUE THREAD

**Issue by linsui** [mgieseki/dvisvgm#146]
1. With tikz, the tex file

```tex
\documentclass[tikz, margin=3pt, dvisvgm]{standalone}
\usepackage{graphicx}

\begin{document}
\begin{tikzpicture}
\node [draw] {\includegraphics[width=1cm]{./test.png}};
\end{tikzpicture}
\end{document}
```

The generate svg file is

```svg
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.11 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='-69.011212 -69.011212 35.385983 35.382665'>
<g id='page1'>
<g stroke-miterlimit='10' transform='translate(-51.318223,-51.31988)scale(0.996264,-0.996264)'>
<g fill='#000' stroke='#000'>
<g stroke-width='0.4'>
<path d='M -17.55934 -17.55768 h 35.11868 v 35.11536 h -35.11868 Z' fill='none'/>
<g transform='translate(-14.22636,-14.2247)'>
<g stroke='none' transform='scale(-1.00375,1.00375)translate(-51.318223,-51.31988)scale(-1,-1)'>
<g fill='#000'>
<g stroke='none'/>
</g>
</g>
</g>
</g>
</g>
</g>
</g>
</svg>
```

2. Without tikz, the tex file

```tex
\documentclass[margin=3pt, dvisvgm]{standalone}
\usepackage{graphicx}

\begin{document}
\includegraphics[width=1cm]{./test.png}
\end{document}
```

The generate svg file is

```svg
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.11 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 0 0'>
<g id='page1'>
<g transform='translate(-69.011212,-69.011121)'> <svg height='28.34311' overflow='visible' viewBox='0 0 500 500' width='28.34637'> <image height='500' width='500' xlink:href='./test.png'/> </svg> </g>
</g>
</svg>
```

I generate the svg with

```
xelatex -no-pdf test
dvisvgm --zoom=-1 --exact --font-format=woff test.xdv
```

**Comment by mgieseki** [comment]
This seems to be a bug in the dvisvgm backend of LaTeX/XeLaTeX. It creates a `pdf:image` special to reference the PNG file which dvisvgm doesn't support. Here's a excerpt of the XDV file:
```
  xxx: 'dvisvgm:raw <g fill="#000">{?nl} '
  xxx: 'dvisvgm:raw <g stroke="none"> '
  push:
    push:
      xxx: 'pdf:image bbox 0 0 479.20183 289.91212 clip 0 width 28.45274pt (./test.png) '
    pop:
  pop:
  right: 28.452744pt
  xxx: 'dvisvgm:raw </g> '
  xxx: 'dvisvgm:raw </g>{?nl} '
```
The missing image in the SVG is expected here and therefore not a bug in dvisvgm. The issue must be fixed in the dvisvgm driver provided by the LaTeX team.
