### ISSUE TITLE
Broken TikZ output on macOS

### ISSUE THREAD

**Issue by davidstraka2** [mgieseki/dvisvgm#157]
When an SVG image is generated from a DVI document containing TikZ output, the resulting SVG is missing any shapes but the text, and all the text is aligned to the top of the image with characters overlapping. This is happening specifically on macOS; on Windows and Linux everything seems to be working.

Software versions used: macOS 10.15.7, MacTeX 2021.0328 (comes with dvisvgm 2.11.1)

Commands used:
1. `latex image.tex`
2. `dvisvgm --no-fonts image.dvi`

The DVI file generated seems to not be the issue, since when the DVI file generated on macOS is copied over to Windows 10 and then the Windows version of dvisvgm (the one included in texlive) is used on that file, the resulting SVG is fine.

TeX source of a simple reproducible example:

```tex
\documentclass[tikz]{standalone}
\begin{document}
  \begin{tikzpicture}[]
    \draw (0,0) -- (1,1) node[pos=0.5]{x};
  \end{tikzpicture}
\end{document}
```

For a comparison of two versions (ok Windows version and broken macOS version) of a more complex SVG (not the one in the simple example above), see the image below.

![comparison](https://user-images.githubusercontent.com/32021723/125235121-3b481c80-e2e2-11eb-8159-286997e64316.png)

A GitHub Actions workflow to generate outputs on macOS and upload job artifacts:

```yml
name: CI
on: [push, pull_request]
jobs:
  Test:
    name: Test macOS
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install MacTex
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install --cask mactex
          echo "/Library/TeX/texbin" >> $GITHUB_PATH
      - name: Process image
        run: |
          latex image.tex
          dvisvgm --no-fonts image.dvi
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            image.dvi
            image.log
            image.svg
```
