### ISSUE TITLE
Compilation error in flatpak texlive extension

### ISSUE THREAD

**Issue by jakobjakobson13** [mgieseki/dvisvgm#275]
Dear all,

in a recent flatpak texlive extension ( https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/pull/164 ) with the following information regarding dvisvgm
 
```
- name: dvisvgm
    build-options:
      cflags: -I/usr/lib/sdk/texlive/include
      cxxflags: -I/usr/lib/sdk/texlive/include
      ldflags: -L/usr/lib/sdk/texlive/lib
      env:
        PKG_CONFIG_PATH: /usr/lib/sdk/texlive/lib/pkgconfig
    config-opts:
      - --bindir=${FLATPAK_DEST}/bin/${FLATPAK_ARCH}-linux
      - --enable-bundled-libs
    sources:
      - type: archive
        url: https://github.com/mgieseki/dvisvgm/releases/download/3.4/dvisvgm-3.4.tar.gz
        sha256: b13125c5e00e6e053b283cca6aaf8419c29f3a1b4ed9617ec7074a79d32de3d7
```
I got a compilation error ( https://buildbot.flathub.org/#/builders/5/builds/18169 ) with the following error message
```
TTFWriter.cpp:26:10: fatal error: woff2/encode.h: No such file or directory
   26 | #include <woff2/encode.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

The compilation failed after the update from dvisvgm-3.2.2 to dvisvgm-3.4. Can you provide me any information? Thank you.
